#! /usr/bin/env bash
set -x
umask 022
pwd
alias whichtest="../which-$WHICH_VERSION/which"

touch cat; chmod 755 cat; pwd
alias

echo "dh whichtest"
whichtest

echo "dh whichtest --version"
whichtest --version

echo "dh whichtest -- --version"
whichtest -- --version

whichtest cat

whichtest --show-tilde cat

whichtest --show-dot cat

whichtest --show-tilde --show-dot cat

whichtest --skip-dot cat

(whichtest cat)
#(cd /bin; whichtest cat)

(whichtest --show-dot cat)
#(cd /bin; whichtest --show-dot cat)

(whichtest --show-dot cat)
#(cd /bin; PATH=".:/bin:/usr/bin" whichtest --show-dot cat)

#(cd /bin; PATH="/bin:.:/usr/bin" whichtest --show-dot cat)
(whichtest --show-dot cat)

(whichtest --skip-dot --show-dot cat)
#(cd /bin; PATH=".:/bin:/usr/bin" whichtest --skip-dot --show-dot cat)

whichtest ls

whichtest xxx &> /dev/null

whichtest ./ls &> /dev/null

#(cd /; whichtest bin/ls)
(whichtest /bin/ls  &> /dev/null)

(whichtest --show-dot /bin/ls)

(whichtest --show-dot /bin/ls)

(whichtest --show-dot bin/xxx)

(whichtest --show-dot /bin/xxx)

whichtest --all cat

touch xxx
whichtest ./xxx

chmod 711 xxx
whichtest ./xxx

chmod 655 cat
whichtest cat

#/usr/bin/sudo /bin/chown root cat
/bin/chown root cat
whichtest cat

#/usr/bin/sudo /bin/chmod 545 cat
/bin/chmod 545 cat
whichtest cat

#/usr/bin/sudo /bin/chgrp bin cat

#/usr/bin/sudo /bin/chmod 541 cat
/bin/chmod 541 cat
whichtest cat
/bin/rm -f cat
#/usr/bin/sudo /bin/rm -f cat

#/usr/bin/sudo /bin/chown root xxx
/bin/chown root xxx
whichtest ./xxx

#/usr/bin/sudo /bin/chmod 700 xxx
/bin/chmod 700 xxx
whichtest ./xxx

id
ls -l xxx
#/usr/bin/sudo /bin/chmod 750 xxx
/bin/chmod 750 xxx
#/usr/bin/sudo /bin/chgrp carlo xxx
#/bin/chgrp carlo xxx
#whichtest ./xxx

#/usr/bin/sudo /bin/chgrp bin xxx
/bin/chgrp bin xxx
whichtest ./xxx

(alias which='alias | whichtest --tty-only --read-alias --show-tilde --show-dot'
alias test1='test1'
alias test2='echo "test2" | cat | sort'
alias test3='  echo "test2"|cat&sort'
alias test4='	ls &&sort ||/usr/bin/which || exit'

pwd
export PATH="${PWD}/../:$PATH"
../which which
../which test1
../which test2
../which test3
../which test4)
